server:
  port: 6001
spring:
  application:
    name: simple-movie-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/

feign:
  hystrix:
    enabled: false